using FolioTrace;
using FolioTrace.Aggregates;
using FolioTrace.Common;

namespace Repository;

public sealed class InitRepository(IEventRepository eventRepository) : IInitRepository
{
    private static readonly (string Alpha2, string Alpha3, short Numeric, string Name)[] InitialCountryCodes =
    [
        ("AD", "AND", 20, "Andorra"),
        ("AE", "ARE", 784, "United Arab Emirates (the)"),
        ("AF", "AFG", 4, "Afghanistan"),
        ("AG", "ATG", 28, "Antigua and Barbuda"),
        ("AI", "AIA", 660, "Anguilla"),
        ("AL", "ALB", 8, "Albania"),
        ("AM", "ARM", 51, "Armenia"),
        ("AO", "AGO", 24, "Angola"),
        ("AQ", "ATA", 10, "Antarctica"),
        ("AR", "ARG", 32, "Argentina"),
        ("AS", "ASM", 16, "American Samoa"),
        ("AT", "AUT", 40, "Austria"),
        ("AU", "AUS", 36, "Australia"),
        ("AW", "ABW", 533, "Aruba"),
        ("AX", "ALA", 248, "Åland Islands"),
        ("AZ", "AZE", 31, "Azerbaijan"),
        ("BA", "BIH", 70, "Bosnia and Herzegovina"),
        ("BB", "BRB", 52, "Barbados"),
        ("BD", "BGD", 50, "Bangladesh"),
        ("BE", "BEL", 56, "Belgium"),
        ("BF", "BFA", 854, "Burkina Faso"),
        ("BG", "BGR", 100, "Bulgaria"),
        ("BH", "BHR", 48, "Bahrain"),
        ("BI", "BDI", 108, "Burundi"),
        ("BJ", "BEN", 204, "Benin"),
        ("BL", "BLM", 652, "Saint Barthélemy"),
        ("BM", "BMU", 60, "Bermuda"),
        ("BN", "BRN", 96, "Brunei Darussalam"),
        ("BO", "BOL", 68, "Bolivia (Plurinational State of)"),
        ("BQ", "BES", 535, "Bonaire, Sint Eustatius and Saba"),
        ("BR", "BRA", 76, "Brazil"),
        ("BS", "BHS", 44, "Bahamas (the)"),
        ("BT", "BTN", 64, "Bhutan"),
        ("BV", "BVT", 74, "Bouvet Island"),
        ("BW", "BWA", 72, "Botswana"),
        ("BY", "BLR", 112, "Belarus"),
        ("BZ", "BLZ", 84, "Belize"),
        ("CA", "CAN", 124, "Canada"),
        ("CC", "CCK", 166, "Cocos (Keeling) Islands (the)"),
        ("CD", "COD", 180, "Congo (the Democratic Republic of the)"),
        ("CF", "CAF", 140, "Central African Republic (the)"),
        ("CG", "COG", 178, "Congo (the)"),
        ("CH", "CHE", 756, "Switzerland"),
        ("CI", "CIV", 384, "Côte d'Ivoire"),
        ("CK", "COK", 184, "Cook Islands (the)"),
        ("CL", "CHL", 152, "Chile"),
        ("CM", "CMR", 120, "Cameroon"),
        ("CN", "CHN", 156, "China"),
        ("CO", "COL", 170, "Colombia"),
        ("CR", "CRI", 188, "Costa Rica"),
        ("CU", "CUB", 192, "Cuba"),
        ("CV", "CPV", 132, "Cabo Verde"),
        ("CW", "CUW", 531, "Curaçao"),
        ("CX", "CXR", 162, "Christmas Island"),
        ("CY", "CYP", 196, "Cyprus"),
        ("CZ", "CZE", 203, "Czechia"),
        ("DE", "DEU", 276, "Germany"),
        ("DJ", "DJI", 262, "Djibouti"),
        ("DK", "DNK", 208, "Denmark"),
        ("DM", "DMA", 212, "Dominica"),
        ("DO", "DOM", 214, "Dominican Republic (the)"),
        ("DZ", "DZA", 12, "Algeria"),
        ("EC", "ECU", 218, "Ecuador"),
        ("EE", "EST", 233, "Estonia"),
        ("EG", "EGY", 818, "Egypt"),
        ("EH", "ESH", 732, "Western Sahara"),
        ("ER", "ERI", 232, "Eritrea"),
        ("ES", "ESP", 724, "Spain"),
        ("ET", "ETH", 231, "Ethiopia"),
        ("FI", "FIN", 246, "Finland"),
        ("FJ", "FJI", 242, "Fiji"),
        ("FK", "FLK", 238, "Falkland Islands (the) [Malvinas]"),
        ("FM", "FSM", 583, "Micronesia (Federated States of)"),
        ("FO", "FRO", 234, "Faroe Islands (the)"),
        ("FR", "FRA", 250, "France"),
        ("GA", "GAB", 266, "Gabon"),
        ("GB", "GBR", 826, "United Kingdom of Great Britain and Northern Ireland (the)"),
        ("GD", "GRD", 308, "Grenada"),
        ("GE", "GEO", 268, "Georgia"),
        ("GF", "GUF", 254, "French Guiana"),
        ("GG", "GGY", 831, "Guernsey"),
        ("GH", "GHA", 288, "Ghana"),
        ("GI", "GIB", 292, "Gibraltar"),
        ("GL", "GRL", 304, "Greenland"),
        ("GM", "GMB", 270, "Gambia (the)"),
        ("GN", "GIN", 324, "Guinea"),
        ("GP", "GLP", 312, "Guadeloupe"),
        ("GQ", "GNQ", 226, "Equatorial Guinea"),
        ("GR", "GRC", 300, "Greece"),
        ("GS", "SGS", 239, "South Georgia and the South Sandwich Islands"),
        ("GT", "GTM", 320, "Guatemala"),
        ("GU", "GUM", 316, "Guam"),
        ("GW", "GNB", 624, "Guinea-Bissau"),
        ("GY", "GUY", 328, "Guyana"),
        ("HK", "HKG", 344, "Hong Kong"),
        ("HM", "HMD", 334, "Heard Island and McDonald Islands"),
        ("HN", "HND", 340, "Honduras"),
        ("HR", "HRV", 191, "Croatia"),
        ("HT", "HTI", 332, "Haiti"),
        ("HU", "HUN", 348, "Hungary"),
        ("ID", "IDN", 360, "Indonesia"),
        ("IE", "IRL", 372, "Ireland"),
        ("IL", "ISR", 376, "Israel"),
        ("IM", "IMN", 833, "Isle of Man"),
        ("IN", "IND", 356, "India"),
        ("IO", "IOT", 86, "British Indian Ocean Territory (the)"),
        ("IQ", "IRQ", 368, "Iraq"),
        ("IR", "IRN", 364, "Iran (Islamic Republic of)"),
        ("IS", "ISL", 352, "Iceland"),
        ("IT", "ITA", 380, "Italy"),
        ("JE", "JEY", 832, "Jersey"),
        ("JM", "JAM", 388, "Jamaica"),
        ("JO", "JOR", 400, "Jordan"),
        ("JP", "JPN", 392, "Japan"),
        ("KE", "KEN", 404, "Kenya"),
        ("KG", "KGZ", 417, "Kyrgyzstan"),
        ("KH", "KHM", 116, "Cambodia"),
        ("KI", "KIR", 296, "Kiribati"),
        ("KM", "COM", 174, "Comoros (the)"),
        ("KN", "KNA", 659, "Saint Kitts and Nevis"),
        ("KP", "PRK", 408, "Korea (the Democratic People's Republic of)"),
        ("KR", "KOR", 410, "Korea (the Republic of)"),
        ("KW", "KWT", 414, "Kuwait"),
        ("KY", "CYM", 136, "Cayman Islands (the)"),
        ("KZ", "KAZ", 398, "Kazakhstan"),
        ("LA", "LAO", 418, "Lao People's Democratic Republic (the)"),
        ("LB", "LBN", 422, "Lebanon"),
        ("LC", "LCA", 662, "Saint Lucia"),
        ("LI", "LIE", 438, "Liechtenstein"),
        ("LK", "LKA", 144, "Sri Lanka"),
        ("LR", "LBR", 430, "Liberia"),
        ("LS", "LSO", 426, "Lesotho"),
        ("LT", "LTU", 440, "Lithuania"),
        ("LU", "LUX", 442, "Luxembourg"),
        ("LV", "LVA", 428, "Latvia"),
        ("LY", "LBY", 434, "Libya"),
        ("MA", "MAR", 504, "Morocco"),
        ("MC", "MCO", 492, "Monaco"),
        ("MD", "MDA", 498, "Moldova (the Republic of)"),
        ("ME", "MNE", 499, "Montenegro"),
        ("MF", "MAF", 663, "Saint Martin (French part)"),
        ("MG", "MDG", 450, "Madagascar"),
        ("MH", "MHL", 584, "Marshall Islands (the)"),
        ("MK", "MKD", 807, "North Macedonia"),
        ("ML", "MLI", 466, "Mali"),
        ("MM", "MMR", 104, "Myanmar"),
        ("MN", "MNG", 496, "Mongolia"),
        ("MO", "MAC", 446, "Macao"),
        ("MP", "MNP", 580, "Northern Mariana Islands (the)"),
        ("MQ", "MTQ", 474, "Martinique"),
        ("MR", "MRT", 478, "Mauritania"),
        ("MS", "MSR", 500, "Montserrat"),
        ("MT", "MLT", 470, "Malta"),
        ("MU", "MUS", 480, "Mauritius"),
        ("MV", "MDV", 462, "Maldives"),
        ("MW", "MWI", 454, "Malawi"),
        ("MX", "MEX", 484, "Mexico"),
        ("MY", "MYS", 458, "Malaysia"),
        ("MZ", "MOZ", 508, "Mozambique"),
        ("NA", "NAM", 516, "Namibia"),
        ("NC", "NCL", 540, "New Caledonia"),
        ("NE", "NER", 562, "Niger (the)"),
        ("NF", "NFK", 574, "Norfolk Island"),
        ("NG", "NGA", 566, "Nigeria"),
        ("NI", "NIC", 558, "Nicaragua"),
        ("NL", "NLD", 528, "Netherlands (the)"),
        ("NO", "NOR", 578, "Norway"),
        ("NP", "NPL", 524, "Nepal"),
        ("NR", "NRU", 520, "Nauru"),
        ("NU", "NIU", 570, "Niue"),
        ("NZ", "NZL", 554, "New Zealand"),
        ("OM", "OMN", 512, "Oman"),
        ("PA", "PAN", 591, "Panama"),
        ("PE", "PER", 604, "Peru"),
        ("PF", "PYF", 258, "French Polynesia"),
        ("PG", "PNG", 598, "Papua New Guinea"),
        ("PH", "PHL", 608, "Philippines (the)"),
        ("PK", "PAK", 586, "Pakistan"),
        ("PL", "POL", 616, "Poland"),
        ("PM", "SPM", 666, "Saint Pierre and Miquelon"),
        ("PN", "PCN", 612, "Pitcairn"),
        ("PR", "PRI", 630, "Puerto Rico"),
        ("PS", "PSE", 275, "Palestine, State of"),
        ("PT", "PRT", 620, "Portugal"),
        ("PW", "PLW", 585, "Palau"),
        ("PY", "PRY", 600, "Paraguay"),
        ("QA", "QAT", 634, "Qatar"),
        ("RE", "REU", 638, "Réunion"),
        ("RO", "ROU", 642, "Romania"),
        ("RS", "SRB", 688, "Serbia"),
        ("RU", "RUS", 643, "Russian Federation (the)"),
        ("RW", "RWA", 646, "Rwanda"),
        ("SA", "SAU", 682, "Saudi Arabia"),
        ("SB", "SLB", 90, "Solomon Islands"),
        ("SC", "SYC", 690, "Seychelles"),
        ("SD", "SDN", 729, "Sudan (the)"),
        ("SE", "SWE", 752, "Sweden"),
        ("SG", "SGP", 702, "Singapore"),
        ("SH", "SHN", 654, "Saint Helena, Ascension and Tristan da Cunha"),
        ("SI", "SVN", 705, "Slovenia"),
        ("SJ", "SJM", 744, "Svalbard and Jan Mayen"),
        ("SK", "SVK", 703, "Slovakia"),
        ("SL", "SLE", 694, "Sierra Leone"),
        ("SM", "SMR", 674, "San Marino"),
        ("SN", "SEN", 686, "Senegal"),
        ("SO", "SOM", 706, "Somalia"),
        ("SR", "SUR", 740, "Suriname"),
        ("SS", "SSD", 728, "South Sudan"),
        ("ST", "STP", 678, "Sao Tome and Principe"),
        ("SV", "SLV", 222, "El Salvador"),
        ("SX", "SXM", 534, "Sint Maarten (Dutch part)"),
        ("SY", "SYR", 760, "Syrian Arab Republic (the)"),
        ("SZ", "SWZ", 748, "Eswatini"),
        ("TC", "TCA", 796, "Turks and Caicos Islands (the)"),
        ("TD", "TCD", 148, "Chad"),
        ("TF", "ATF", 260, "French Southern Territories (the)"),
        ("TG", "TGO", 768, "Togo"),
        ("TH", "THA", 764, "Thailand"),
        ("TJ", "TJK", 762, "Tajikistan"),
        ("TK", "TKL", 772, "Tokelau"),
        ("TL", "TLS", 626, "Timor-Leste"),
        ("TM", "TKM", 795, "Turkmenistan"),
        ("TN", "TUN", 788, "Tunisia"),
        ("TO", "TON", 776, "Tonga"),
        ("TR", "TUR", 792, "Turkey"),
        ("TT", "TTO", 780, "Trinidad and Tobago"),
        ("TV", "TUV", 798, "Tuvalu"),
        ("TW", "TWN", 158, "Taiwan (Province of China)"),
        ("TZ", "TZA", 834, "Tanzania, the United Republic of"),
        ("UA", "UKR", 804, "Ukraine"),
        ("UG", "UGA", 800, "Uganda"),
        ("UM", "UMI", 581, "United States Minor Outlying Islands (the)"),
        ("US", "USA", 840, "United States of America (the)"),
        ("UY", "URY", 858, "Uruguay"),
        ("UZ", "UZB", 860, "Uzbekistan"),
        ("VA", "VAT", 336, "Holy See (the)"),
        ("VC", "VCT", 670, "Saint Vincent and the Grenadines"),
        ("VE", "VEN", 862, "Venezuela (Bolivarian Republic of)"),
        ("VG", "VGB", 92, "Virgin Islands (British)"),
        ("VI", "VIR", 850, "Virgin Islands (U.S.)"),
        ("VN", "VNM", 704, "Viet Nam"),
        ("VU", "VUT", 548, "Vanuatu"),
        ("WF", "WLF", 876, "Wallis and Futuna"),
        ("WS", "WSM", 882, "Samoa"),
        ("YE", "YEM", 887, "Yemen"),
        ("YT", "MYT", 175, "Mayotte"),
        ("ZA", "ZAF", 710, "South Africa"),
        ("ZM", "ZMB", 894, "Zambia"),
        ("ZW", "ZWE", 716, "Zimbabwe"),
    ];
    public async Task Build(CancellationToken cancellationToken = default)
    {
        await DeleteEvents(cancellationToken);
        await CreateSetupEvents(cancellationToken);
    }

    private async Task DeleteEvents(CancellationToken cancellationToken)
    {
        await eventRepository.ClearAsync(cancellationToken);
    }

    private async Task CreateSetupEvents(CancellationToken cancellationToken)
    {
        await CreateCountrySetupEvents(cancellationToken);
    }

    private async Task CreateCountrySetupEvents(CancellationToken cancellationToken)
    {
        await StoreEvents<Countries, CountryCreatedEvent>(
            Constants.Initialisation.CountriesStreamId,
            CreateInitialCountryCreatedEvents(),
            cancellationToken);
    }

    public static IReadOnlyList<CountryCreatedEvent> CreateInitialCountryCreatedEvents() =>
        InitialCountryCodes
            .Select(country => CountryCreatedEventBuilder.Create(
                Guid.NewGuid(),
                Constants.Initialisation.EventDateTime,
                Constants.Initialisation.AuditDateTime,
                Constants.Initialisation.Reason,
                country.Alpha2,
                country.Alpha3,
                country.Numeric,
                country.Name))
            .ToList();

    private async Task StoreEvents<TAggregate, TEvent>(Guid streamId, IEnumerable<TEvent> events, CancellationToken cancellationToken)
        where TAggregate : class, IAggregate
        where TEvent : class, IEventBase
    {
        if (events is null)
            throw new ArgumentNullException(nameof(events));

        var eventData = events.ToList();
        if (eventData.Count == 0)
            return;

        await eventRepository.StartStreamAsync<TAggregate, TEvent>(streamId, eventData, cancellationToken);
    }
}

