using System.Text.Json.Serialization;
using FolioTrace.Aggregates;
using FolioTrace.Types;

namespace FolioTrace.Common;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[JsonDerivedType(typeof(AccountCreatedEvent), nameof(AccountCreatedEvent))]
[JsonDerivedType(typeof(AccountModifiedEvent), nameof(AccountModifiedEvent))]
[JsonDerivedType(typeof(AccountActiveModifiedEvent), nameof(AccountActiveModifiedEvent))]
[JsonDerivedType(typeof(AccountDisplayOrderSetEvent), nameof(AccountDisplayOrderSetEvent))]
[JsonDerivedType(typeof(BrokerCreatedEvent), nameof(BrokerCreatedEvent))]
[JsonDerivedType(typeof(BrokerModifiedEvent), nameof(BrokerModifiedEvent))]
[JsonDerivedType(typeof(BrokerActiveSetEvent), nameof(BrokerActiveSetEvent))]
[JsonDerivedType(typeof(BrokerApprovedDateTimeSetEvent), nameof(BrokerApprovedDateTimeSetEvent))]
[JsonDerivedType(typeof(BrokerNextReviewSetEvent), nameof(BrokerNextReviewSetEvent))]
[JsonDerivedType(typeof(BrokerNotesSetEvent), nameof(BrokerNotesSetEvent))]
[JsonDerivedType(typeof(CountryCreatedEvent), nameof(CountryCreatedEvent))]
[JsonDerivedType(typeof(CountryModifiedEvent), nameof(CountryModifiedEvent))]
[JsonDerivedType(typeof(CountryFlagModifiedEvent), nameof(CountryFlagModifiedEvent))]
[JsonDerivedType(typeof(CurrencyCreatedEvent), nameof(CurrencyCreatedEvent))]
[JsonDerivedType(typeof(CurrencyModifiedEvent), nameof(CurrencyModifiedEvent))]
[JsonDerivedType(typeof(FXCreatedEvent), nameof(FXCreatedEvent))]
[JsonDerivedType(typeof(FXActiveModifiedEvent), nameof(FXActiveModifiedEvent))]
[JsonDerivedType(typeof(FXRateSetEvent), nameof(FXRateSetEvent))]
[JsonDerivedType(typeof(FoleoTraderOrderSubmittedEvent), nameof(FoleoTraderOrderSubmittedEvent))]
[JsonDerivedType(typeof(FoleoTraderExecutionReceivedEvent), nameof(FoleoTraderExecutionReceivedEvent))]
[JsonDerivedType(typeof(FoleoTraderOrderFailedEvent), nameof(FoleoTraderOrderFailedEvent))]
[JsonDerivedType(typeof(HoldingPositionMemoCreatedEvent), nameof(HoldingPositionMemoCreatedEvent))]
[JsonDerivedType(typeof(HoldingPositionCashCreatedEvent), nameof(HoldingPositionCashCreatedEvent))]
[JsonDerivedType(typeof(HoldingPositionAssetCreatedEvent), nameof(HoldingPositionAssetCreatedEvent))]
[JsonDerivedType(typeof(HoldingCashDebtCreatedEvent), nameof(HoldingCashDebtCreatedEvent))]
[JsonDerivedType(typeof(HoldingCashInvestableCreatedEvent), nameof(HoldingCashInvestableCreatedEvent))]
[JsonDerivedType(typeof(HoldingCashNonInvestableCreatedEvent), nameof(HoldingCashNonInvestableCreatedEvent))]
[JsonDerivedType(typeof(HoldingInflowCreatedEvent), nameof(HoldingInflowCreatedEvent))]
[JsonDerivedType(typeof(HoldingOutflowCreatedEvent), nameof(HoldingOutflowCreatedEvent))]
[JsonDerivedType(typeof(HoldingInSpecieInCreatedEvent), nameof(HoldingInSpecieInCreatedEvent))]
[JsonDerivedType(typeof(HoldingInSpecieOutCreatedEvent), nameof(HoldingInSpecieOutCreatedEvent))]
[JsonDerivedType(typeof(HoldingFeesCustodianCreatedEvent), nameof(HoldingFeesCustodianCreatedEvent))]
[JsonDerivedType(typeof(HoldingFeesAdministratorCreatedEvent), nameof(HoldingFeesAdministratorCreatedEvent))]
[JsonDerivedType(typeof(HoldingFeesBankCreatedEvent), nameof(HoldingFeesBankCreatedEvent))]
[JsonDerivedType(typeof(HoldingIncomeCreatedEvent), nameof(HoldingIncomeCreatedEvent))]
[JsonDerivedType(typeof(HoldingInterestCreatedEvent), nameof(HoldingInterestCreatedEvent))]
[JsonDerivedType(typeof(HoldingPositionMemoModifiedEvent), nameof(HoldingPositionMemoModifiedEvent))]
[JsonDerivedType(typeof(HoldingPositionCashModifiedEvent), nameof(HoldingPositionCashModifiedEvent))]
[JsonDerivedType(typeof(HoldingPositionAssetModifiedEvent), nameof(HoldingPositionAssetModifiedEvent))]
[JsonDerivedType(typeof(HoldingCashDebtModifiedEvent), nameof(HoldingCashDebtModifiedEvent))]
[JsonDerivedType(typeof(HoldingCashInvestableModifiedEvent), nameof(HoldingCashInvestableModifiedEvent))]
[JsonDerivedType(typeof(HoldingCashNonInvestableModifiedEvent), nameof(HoldingCashNonInvestableModifiedEvent))]
[JsonDerivedType(typeof(HoldingInflowModifiedEvent), nameof(HoldingInflowModifiedEvent))]
[JsonDerivedType(typeof(HoldingOutflowModifiedEvent), nameof(HoldingOutflowModifiedEvent))]
[JsonDerivedType(typeof(HoldingInSpecieInModifiedEvent), nameof(HoldingInSpecieInModifiedEvent))]
[JsonDerivedType(typeof(HoldingInSpecieOutModifiedEvent), nameof(HoldingInSpecieOutModifiedEvent))]
[JsonDerivedType(typeof(HoldingFeesCustodianModifiedEvent), nameof(HoldingFeesCustodianModifiedEvent))]
[JsonDerivedType(typeof(HoldingFeesAdministratorModifiedEvent), nameof(HoldingFeesAdministratorModifiedEvent))]
[JsonDerivedType(typeof(HoldingFeesBankModifiedEvent), nameof(HoldingFeesBankModifiedEvent))]
[JsonDerivedType(typeof(HoldingIncomeModifiedEvent), nameof(HoldingIncomeModifiedEvent))]
[JsonDerivedType(typeof(HoldingInterestModifiedEvent), nameof(HoldingInterestModifiedEvent))]
[JsonDerivedType(typeof(HoldingActiveModifiedEvent), nameof(HoldingActiveModifiedEvent))]
[JsonDerivedType(typeof(InstrumentCreatedEvent), nameof(InstrumentCreatedEvent))]
[JsonDerivedType(typeof(InstrumentModifiedEvent), nameof(InstrumentModifiedEvent))]
[JsonDerivedType(typeof(InstrumentActiveModifiedEvent), nameof(InstrumentActiveModifiedEvent))]
[JsonDerivedType(typeof(InstrumentIdentifierSetEvent), nameof(InstrumentIdentifierSetEvent))]
[JsonDerivedType(typeof(InstrumentIdentifierUnsetEvent), nameof(InstrumentIdentifierUnsetEvent))]
[JsonDerivedType(typeof(InstrumentTermsSetEvent), nameof(InstrumentTermsSetEvent))]
[JsonDerivedType(typeof(InstrumentPriceSetEvent), nameof(InstrumentPriceSetEvent))]
[JsonDerivedType(typeof(InstrumentIncomeSetEvent), nameof(InstrumentIncomeSetEvent))]
[JsonDerivedType(typeof(TransactionCreditEvent), nameof(TransactionCreditEvent))]
[JsonDerivedType(typeof(TransactionDebitEvent), nameof(TransactionDebitEvent))]
[JsonDerivedType(typeof(TransactionCancellationEvent), nameof(TransactionCancellationEvent))]
[JsonDerivedType(typeof(TicketCreatedEvent), nameof(TicketCreatedEvent))]
[JsonDerivedType(typeof(TicketAccountAddedEvent), nameof(TicketAccountAddedEvent))]
[JsonDerivedType(typeof(TicketAccountRemovedEvent), nameof(TicketAccountRemovedEvent))]
[JsonDerivedType(typeof(TicketProposalCreatedEvent), nameof(TicketProposalCreatedEvent))]
[JsonDerivedType(typeof(TicketProposalModifiedEvent), nameof(TicketProposalModifiedEvent))]
[JsonDerivedType(typeof(TicketProposalDecisionRequestedEvent), nameof(TicketProposalDecisionRequestedEvent))]
[JsonDerivedType(typeof(TicketProposalApprovedEvent), nameof(TicketProposalApprovedEvent))]
[JsonDerivedType(typeof(TicketProposalNotApprovedEvent), nameof(TicketProposalNotApprovedEvent))]
[JsonDerivedType(typeof(TicketProposalReasonSetEvent), nameof(TicketProposalReasonSetEvent))]
[JsonDerivedType(typeof(TicketProposalAllocationSetEvent), nameof(TicketProposalAllocationSetEvent))]
[JsonDerivedType(typeof(TicketTradeCreatedEvent), nameof(TicketTradeCreatedEvent))]
[JsonDerivedType(typeof(TicketTradeModifiedEvent), nameof(TicketTradeModifiedEvent))]
[JsonDerivedType(typeof(TicketTradeFillAddedEvent), nameof(TicketTradeFillAddedEvent))]
[JsonDerivedType(typeof(TicketTradeFillModifiedEvent), nameof(TicketTradeFillModifiedEvent))]
[JsonDerivedType(typeof(TicketTradeFillRemovedEvent), nameof(TicketTradeFillRemovedEvent))]
[JsonDerivedType(typeof(TicketTradeDecisionRequestedEvent), nameof(TicketTradeDecisionRequestedEvent))]
[JsonDerivedType(typeof(TicketTradeApprovedEvent), nameof(TicketTradeApprovedEvent))]
[JsonDerivedType(typeof(TicketTradeNotApprovedEvent), nameof(TicketTradeNotApprovedEvent))]
[JsonDerivedType(typeof(TicketTradeInstructionNotesSetEvent), nameof(TicketTradeInstructionNotesSetEvent))]
[JsonDerivedType(typeof(TicketTradeProgressNotesSetEvent), nameof(TicketTradeProgressNotesSetEvent))]
[JsonDerivedType(typeof(TicketCancelledEvent), nameof(TicketCancelledEvent))]
[JsonDerivedType(typeof(UserCreatedEvent), nameof(UserCreatedEvent))]
[JsonDerivedType(typeof(UserModifiedEvent), nameof(UserModifiedEvent))]
[JsonDerivedType(typeof(UserSignedInEvent), nameof(UserSignedInEvent))]
[JsonDerivedType(typeof(UserSignedOutEvent), nameof(UserSignedOutEvent))]
[JsonDerivedType(typeof(UserMenuPreferencesCreatedEvent), nameof(UserMenuPreferencesCreatedEvent))]
[JsonDerivedType(typeof(UserMenuPreferencesModifiedEvent), nameof(UserMenuPreferencesModifiedEvent))]
[JsonDerivedType(typeof(UserValuationPreferencesCreatedEvent), nameof(UserValuationPreferencesCreatedEvent))]
[JsonDerivedType(typeof(UserValuationPreferencesModifiedEvent), nameof(UserValuationPreferencesModifiedEvent))]
[JsonDerivedType(typeof(UserBookmarkCreatedEvent), nameof(UserBookmarkCreatedEvent))]
[JsonDerivedType(typeof(UserBookmarkModifiedEvent), nameof(UserBookmarkModifiedEvent))]
[JsonDerivedType(typeof(UserBookmarkDisplayOrderSetEvent), nameof(UserBookmarkDisplayOrderSetEvent))]
[JsonDerivedType(typeof(UserBookmarkDeletedEvent), nameof(UserBookmarkDeletedEvent))]
public interface IEventBase : IType
{
    [EventProperty(Description = "Event type", Order = 0)]
    string Type { get; }

    [EventProperty(Description = "Event ID", Order = 10)]
    EventID EventID { get; }

    [EventProperty(Description = "User ID", Order = 20)]
    UserID UserID { get; }

    [EventProperty(Description = "Event time", Order = 30)]
    EventDateTime EventDateTime { get; }

    [EventProperty(Description = "Audit time", Order = 40)]
    AuditDateTime AuditDateTime { get; }

    [EventProperty(Description = "Reason", Order = 50)]
    string Reason { get; }
}
