@repository_HostAddress = https://localhost:7058/API

GET {{repository_HostAddress}}/Countries/?eventDateTime=2026-05-17T23:59:59
Accept: application/json

###

GET {{repository_HostAddress}}/Events/Country/
Accept: application/json

###
